In [20]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency

In [4]:
df = pd.read_csv("Customer Satisfaction Scores and Behavior Data.csv")
df.head()

,Customer_ID,Group,Satisfaction_Score,Age,Gender,Location,Purchase_History,Support_Contacted,Loyalty_Level,Satisfaction_Factor
0,81-237-4704,A,6,55,Male,Phoenix.AZ,Yes,No,Low,Price
1,14-117-0504,A,7,46,Female,Los Angeles.CA,Yes,No,Low,Product Variety
2,21-336-6416,A,7,55,Female,Houston.TX,Yes,Yes,Low,Packaging
3,59-781-3650,A,1,42,Male,Los Angeles.CA,Yes,No,Medium,Price
4,52-712-5734,B,9,37,Male,Austin.TX,Yes,Yes,Medium,Packaging

In [5]:
data = df[['Gender', 'Purchase_History']]
data.head()

   Gender Purchase_History
0    Male              Yes
1  Female              Yes
2  Female              Yes
3    Male              Yes
4    Male              Yes

In [18]:
df1 = pd.DataFrame()
df1['Gender'] = ['Male', 'Female']
df1['Purchase_History_Yes'] = [
    len(
        data[(data['Purchase_History'] == 'Yes') & (data['Gender'] == 'Male')]
    ),
    len(
        data[(data['Purchase_History'] == 'Yes') & (data['Gender'] == 'Female')]
    )
]
df1['Purchase_History_No'] = [
    len(
        data[(data['Purchase_History'] == 'No') & (data['Gender'] == 'Male')]
    ),
    len(
        data[(data['Purchase_History'] == 'No') & (data['Gender'] == 'Female')]
    )
]
df1.head()

   Gender  Purchase_History_Yes  Purchase_History_No
0    Male                    30                   24
1  Female                    39                   27

In [19]:
table = pd.crosstab(
    data['Gender'],
    data['Purchase_History']
)

print(table)

Purchase_History  No  Yes
Gender
Female            27   39
Male              24   30

In [21]:
chi2, p, dof, expected = chi2_contingency(table)

expected_df = pd.DataFrame(
    expected,
    index = table.index,
    columns = table.columns
)

print(expected_df)

Purchase_History     No    Yes
Gender
Female            28.05  37.95
Male              22.95  31.05

In [23]:
print("Degree of Freedom: ", dof)
print("p value: ", p)
print("chi2: ", chi2)

Degree of Freedom:  1
p value:  0.838233824020272
chi2:  0.04167850715165294

In [24]:
alpha = 0.05

if (p < 0.05):
    print("Null Hypothesis Rejected")
    print("Gender and purchase history are dependent")
else:
    print("Failed to reject Null Hypothesis")
    print("Gender and purchase history are independent")

Failed to reject Null Hypothesis
Gender and purchase history are independent