In [3]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind

In [4]:
df = pd.read_csv("Customer Satisfaction Scores and Behavior Data.csv")
df.head()

,Customer_ID,Group,Satisfaction_Score,Age,Gender,Location,Purchase_History,Support_Contacted,Loyalty_Level,Satisfaction_Factor
0,81-237-4704,A,6,55,Male,Phoenix.AZ,Yes,No,Low,Price
1,14-117-0504,A,7,46,Female,Los Angeles.CA,Yes,No,Low,Product Variety
2,21-336-6416,A,7,55,Female,Houston.TX,Yes,Yes,Low,Packaging
3,59-781-3650,A,1,42,Male,Los Angeles.CA,Yes,No,Medium,Price
4,52-712-5734,B,9,37,Male,Austin.TX,Yes,Yes,Medium,Packaging

In [5]:
data = df[['Group', 'Satisfaction_Score']]
data.head()

  Group  Satisfaction_Score
0     A                   6
1     A                   7
2     A                   7
3     A                   1
4     B                   9

In [6]:
a_sat = np.array(data['Satisfaction_Score'][data['Group'] == 'A'])
b_sat = np.array(data['Satisfaction_Score'][data['Group'] == 'B'])

In [7]:
t_stat, p_value = ttest_ind(
    a_sat,
    b_sat,
    equal_var = False
)

print("t statistic: ", t_stat)
print("p value: ", p_value)

t statistic:  -0.6680164626639695
p value:  0.5056151446204256

In [8]:
alpha = 0.05

if p_value < alpha:
    print("Null Hypothesis Rejected")
    print("There is a significant difference between the average satisfaction scores of Groups A and B")
else:
    print("Failed to Reject Null Hypothesis")
    print("There is no significant difference between the average satisfaction scores of Groups A and B")

Failed to Reject Null Hypothesis
There is no significant difference between the average satisfaction scores of Groups A and B