# **Levene's Test and F-Test**

### **Null Hypothesis**: There is no significant difference between the variances of Groups A and B

### **Alternative Hypothesis**: There is a significant difference between the variances of Groups A and B

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import levene, f

In [2]:
df = pd.read_csv("Customer Satisfaction Scores and Behavior Data.csv")
df.head()

,Customer_ID,Group,Satisfaction_Score,Age,Gender,Location,Purchase_History,Support_Contacted,Loyalty_Level,Satisfaction_Factor
0,81-237-4704,A,6,55,Male,Phoenix.AZ,Yes,No,Low,Price
1,14-117-0504,A,7,46,Female,Los Angeles.CA,Yes,No,Low,Product Variety
2,21-336-6416,A,7,55,Female,Houston.TX,Yes,Yes,Low,Packaging
3,59-781-3650,A,1,42,Male,Los Angeles.CA,Yes,No,Medium,Price
4,52-712-5734,B,9,37,Male,Austin.TX,Yes,Yes,Medium,Packaging

In [3]:
data = df[["Group", "Satisfaction_Score"]]
data.head()

  Group  Satisfaction_Score
0     A                   6
1     A                   7
2     A                   7
3     A                   1
4     B                   9

In [4]:
data["Group"].unique()

array(['A', 'B'], dtype=object)

In [5]:
a_group = np.array(data[data["Group"] == 'A']['Satisfaction_Score'])
b_group = np.array(data[data["Group"] == 'B']['Satisfaction_Score'])

In [6]:
stat, p = levene(a_group, b_group)
print("Levene Statistic: ", stat)
print("p value: ", p)

Levene Statistic:  0.21663300899577734
p value:  0.6424753309842643

In [7]:
alpha = 0.05

if p < alpha:
    print("Rejected Null Hypothesis")
    print("There is a significant difference between the variances of Groups A and B")
else:
    print("Failed to Reject Null Hypothesis")
    print("There is no significant difference between the variances of Groups A and B")

Failed to Reject Null Hypothesis
There is no significant difference between the variances of Groups A and B

In [8]:
a_var = np.var(a_group, ddof = 1)
b_var = np.var(b_group, ddof = 1)

print("Variance of Group A: ", a_var)
print("Variance of Group B: ", b_var)

Variance of Group A:  8.835106382978724
Variance of Group B:  9.43661971830986

In [9]:
if a_var > b_var:
    F = a_var / b_var
    dfn = len(a_group) - 1
    ddn = len(b_group) - 1
else:
    F = b_var / a_var
    dfn = len(a_group) - 1
    ddn = len(b_group) - 1

print("F-statistic: ", F)

F-statistic:  1.0680821836497614

In [10]:
p_value = 2 * min(
    f.cdf(F, dfn, ddn),
    1 - f.cdf(F, dfn, ddn)
)

print("p value: ", p_value)

p value:  0.7908486015223257

In [11]:
alpha = 0.05

if p_value < alpha:
    print("Rejected Null Hypothesis")
    print("There is a significant difference between the variances of Groups A and B")
else:
    print("Failed to Reject Null Hypothesis")
    print("There is no significant difference between the variances of Groups A and B")

Failed to Reject Null Hypothesis
There is no significant difference between the variances of Groups A and B