# **One Way ANOVA**

### **Null Hypothesis**: There is no significant difference between satisfaction scores of customers of different loyalty levels.

### **Alternative Hypothesis**: There is a significant difference between satisfaction scores of customers of different loyalty levels.

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import f_oneway

In [2]:
df = pd.read_csv("Customer Satisfaction Scores and Behavior Data.csv")
df.head()

,Customer_ID,Group,Satisfaction_Score,Age,Gender,Location,Purchase_History,Support_Contacted,Loyalty_Level,Satisfaction_Factor
0,81-237-4704,A,6,55,Male,Phoenix.AZ,Yes,No,Low,Price
1,14-117-0504,A,7,46,Female,Los Angeles.CA,Yes,No,Low,Product Variety
2,21-336-6416,A,7,55,Female,Houston.TX,Yes,Yes,Low,Packaging
3,59-781-3650,A,1,42,Male,Los Angeles.CA,Yes,No,Medium,Price
4,52-712-5734,B,9,37,Male,Austin.TX,Yes,Yes,Medium,Packaging

In [3]:
data = df[["Loyalty_Level", "Satisfaction_Score"]]
data.head()

  Loyalty_Level  Satisfaction_Score
0           Low                   6
1           Low                   7
2           Low                   7
3        Medium                   1
4        Medium                   9

In [4]:
data["Loyalty_Level"].unique()

array(['Low', 'Medium', 'High'], dtype=object)

In [8]:
low_sat = np.array(data[data["Loyalty_Level"] == "Low"]["Satisfaction_Score"])
medium_sat = np.array(data[data["Loyalty_Level"] == "Medium"]["Satisfaction_Score"])
high_sat = np.array(data[data["Loyalty_Level"] == "High"]["Satisfaction_Score"])

In [9]:
f_stat, p_value = f_oneway(
    low_sat,
    medium_sat,
    high_sat
)

print("f statistic: ", f_stat)
print("p value: ", p_value)

f statistic:  2.4323008924319325
p value:  0.09226454646467641

In [10]:
alpha = 0.05

if p_value < alpha:
    print("Null Hypothesis Rejected")
    print("There is a significant difference between the satisfaction scores of customers of different loyalty levels")
else:
    print("Failed to Reject Null Hypothesis")
    print("There is no signigicant difference between the satisfaction scores of customers of different loyalty levels")

Failed to Reject Null Hypothesis
There is no signigicant difference between the satisfaction scores of customers of different loyalty levels