In [1]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_rel

In [2]:
df = pd.read_csv("Customer Satisfaction Scores and Behavior Data.csv")
df.head()

,Customer_ID,Group,Satisfaction_Score,Age,Gender,Location,Purchase_History,Support_Contacted,Loyalty_Level,Satisfaction_Factor
0,81-237-4704,A,6,55,Male,Phoenix.AZ,Yes,No,Low,Price
1,14-117-0504,A,7,46,Female,Los Angeles.CA,Yes,No,Low,Product Variety
2,21-336-6416,A,7,55,Female,Houston.TX,Yes,Yes,Low,Packaging
3,59-781-3650,A,1,42,Male,Los Angeles.CA,Yes,No,Medium,Price
4,52-712-5734,B,9,37,Male,Austin.TX,Yes,Yes,Medium,Packaging

In [3]:
data = df[["Satisfaction_Score", "Support_Contacted"]]
data.head()

   Satisfaction_Score Support_Contacted
0                   6                No
1                   7                No
2                   7               Yes
3                   1                No
4                   9               Yes

In [5]:
t_stat, p_value = ttest_rel(sample_before, sample_after)

print("t statistic: ", t_stat)
print("p value: ", p_value)

ValueError: Array shapes are incompatible for broadcasting.

In [6]:
sample_before = np.array(data['Satisfaction_Score'][data['Support_Contacted'] == 'No'])
sample_after = np.array(data['Satisfaction_Score'][data['Support_Contacted'] == 'Yes'])

In [ ]:
alpha = 0.05

if p_value < alpha:
    print("Null Hypothesis Rejected")
    print("There is a significant difference between satisfaction scores before and after contacting support")
else:
    print("Failed to Reject Null Hypothesis")
    print("There is no significant difference between satisfaction scores before and after contacting support")